/*******************************************************************************
 * Copyright 2008(c) The OBiBa Consortium. All rights reserved.
 * 
 * This program and the accompanying materials
 * are made available under the terms of the GNU Public License v3.0.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package org.obiba.opal.web.security;

import java.lang.reflect.Method;
import java.net.URI;
import java.util.Set;

import javax.ws.rs.HttpMethod;
import javax.ws.rs.Path;
import javax.ws.rs.WebApplicationException;
import javax.ws.rs.core.HttpHeaders;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.UriInfo;
import javax.ws.rs.ext.ExceptionMapper;

import org.apache.shiro.mgt.SessionsSecurityManager;
import org.jboss.resteasy.annotations.interception.Precedence;
import org.jboss.resteasy.annotations.interception.ServerInterceptor;
import org.jboss.resteasy.core.ResourceMethod;
import org.jboss.resteasy.core.ServerResponse;
import org.jboss.resteasy.spi.DefaultOptionsMethodException;
import org.jboss.resteasy.spi.Failure;
import org.jboss.resteasy.spi.HttpRequest;
import org.jboss.resteasy.spi.interception.PostProcessInterceptor;
import org.jboss.resteasy.spi.interception.PreProcessInterceptor;
import org.jboss.resteasy.util.IsHttpMethod;
import org.obiba.opal.core.service.SubjectAclService;
import org.obiba.opal.web.ws.inject.RequestAttributesProvider;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.web.context.request.RequestAttributes;

import com.google.common.base.Predicate;
import com.google.common.collect.ImmutableSet;
import com.google.common.collect.Iterables;
import com.google.common.collect.Sets;

@Component
@ServerInterceptor
@Precedence("HEADER_DECORATOR")
public class AuthorizationInterceptor extends AbstractSecurityComponent implements PreProcessInterceptor, PostProcessInterceptor, ExceptionMapper<DefaultOptionsMethodException> {

  private static final Logger log = LoggerFactory.getLogger(AuthorizationInterceptor.class);

  private static final String OPAL_ALLOW_ATTR = "__OPAL_ALLOW__";

  private static final String ALLOW_HTTP_HEADER = "Allow";

  private final SubjectAclService subjectAclService;

  private final RequestAttributesProvider requestAttributeProvider;

  @Autowired
  public AuthorizationInterceptor(SessionsSecurityManager securityManager, SubjectAclService subjectAclService, RequestAttributesProvider requestAttributeProvider) {
    super(securityManager);
    this.subjectAclService = subjectAclService;
    this.requestAttributeProvider = requestAttributeProvider;
  }

  @Override
  public ServerResponse preProcess(HttpRequest request, ResourceMethod method) throws Failure, WebApplicationException {
    if(HttpMethod.GET.equals(request.getHttpMethod())) {
      computeAllowHeader(request, method);
    } else if(HttpMethod.DELETE.equals(request.getHttpMethod())) {
      // TODO: delete acl entries for the resource and all sub-resources
    }
    return null;
  }

  @Override
  public void postProcess(ServerResponse response) {
    Set<String> allow = (Set<String>) requestAttributeProvider.currentRequestAttributes().getAttribute(OPAL_ALLOW_ATTR, RequestAttributes.SCOPE_REQUEST);
    if(allow != null) {
      response.getMetadata().add(ALLOW_HTTP_HEADER, asHeader(allow));
    }

    if(response.getStatus() == 201) {
      // Add permissions
      URI resourceUri = (URI) response.getMetadata().getFirst(HttpHeaders.LOCATION);
      if(resourceUri == null) {
        throw new IllegalStateException("Missing Location header in 201 response");
      }

      String resource = requestAttributeProvider.getResourcePath(resourceUri);
      if(getSubject().isPermitted("magma:" + resource + ":*") == false) {
        subjectAclService.addSubjectPermission("magma", resource, getSubject().getPrincipal().toString(), "*:*");
      }
    }
  }

  @Override
  public Response toResponse(DefaultOptionsMethodException exception) {
    Response response = exception.getResponse();
    // Extract the Allow header generated by RestEASY. This contains all the methods of the resource class for the given
    // path
    String availableMethods = (String) response.getMetadata().getFirst(ALLOW_HTTP_HEADER);
    UriInfo uri = requestAttributeProvider.getUriInfo();
    return allow(allowed(uri.getPath(), ImmutableSet.of(availableMethods.split(", "))));
  }

  private Response allow(Set<String> allowed) {
    return Response.ok().header(ALLOW_HTTP_HEADER, asHeader(allowed)).build();
  }

  private String asHeader(Iterable<String> values) {
    StringBuilder sb = new StringBuilder();
    for(String s : values) {
      if(sb.length() > 0) sb.append(", ");
      sb.append(s);
    }
    return sb.toString();
  }

  private void computeAllowHeader(HttpRequest request, ResourceMethod method) {
    Set<String> allowed = allowed(request, method);
    requestAttributeProvider.currentRequestAttributes().setAttribute(OPAL_ALLOW_ATTR, allowed, RequestAttributes.SCOPE_REQUEST);
  }

  private Set<String> allowed(final String uri, Set<String> availableMethods) {
    return ImmutableSet.copyOf(Iterables.filter(availableMethods, new Predicate<String>() {

      @Override
      public boolean apply(String from) {
        String perm = "magma:" + uri + ":" + from;
        boolean permitted = getSubject().isPermitted(perm);
        log.info("isPermitted({}, {})=={}", new Object[] { getSubject().getPrincipal(), perm, permitted });
        return permitted;
      }

    }));
  }

  private Set<String> allowed(final HttpRequest request, ResourceMethod method) {
    return allowed(request.getUri().getPath(), availableMethods(method));
  }

  private Set<String> availableMethods(ResourceMethod method) {
    Set<String> availableMethods = Sets.newHashSet();
    String path = getPath(method);
    for(Method otherMethod : method.getResourceClass().getMethods()) {
      Set<String> patate = IsHttpMethod.getHttpMethods(otherMethod);
      if(patate != null && isSamePath(otherMethod, path)) {
        availableMethods.addAll(patate);
      }
    }
    return availableMethods;
  }

  private String getPath(ResourceMethod method) {
    return getPath(method.getMethod());
  }

  private String getPath(Method method) {
    Path path = method.getAnnotation(Path.class);
    return path != null ? path.value() : "";
  }

  /**
   * @param otherMethod
   * @param path
   * @return
   */
  private boolean isSamePath(Method otherMethod, String path) {
    return path.equals(getPath(otherMethod));
  }
}
