/*******************************************************************************
 * Copyright 2008(c) The OBiBa Consortium. All rights reserved.
 * 
 * This program and the accompanying materials
 * are made available under the terms of the GNU Public License v3.0.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package org.obiba.opal.web.gwt.app.client.fs.presenter;

import net.customware.gwt.presenter.client.EventBus;
import net.customware.gwt.presenter.client.place.Place;
import net.customware.gwt.presenter.client.place.PlaceRequest;
import net.customware.gwt.presenter.client.widget.WidgetDisplay;
import net.customware.gwt.presenter.client.widget.WidgetPresenter;

import org.obiba.opal.web.gwt.app.client.fs.event.FileSystemTreeFolderSelectionChangeEvent;
import org.obiba.opal.web.gwt.app.client.fs.event.FileUploadedEvent;
import org.obiba.opal.web.gwt.app.client.fs.event.FolderSelectionChangeEvent;
import org.obiba.opal.web.gwt.app.client.ui.HasFieldUpdater;
import org.obiba.opal.web.gwt.rest.client.ResourceCallback;
import org.obiba.opal.web.gwt.rest.client.ResourceRequestBuilderFactory;
import org.obiba.opal.web.model.client.FileDto;

import com.google.gwt.cell.client.FieldUpdater;
import com.google.gwt.core.client.GWT;
import com.google.gwt.http.client.Response;
import com.google.inject.Inject;

public class FolderDetailsPresenter extends WidgetPresenter<FolderDetailsPresenter.Display> {

  public interface Display extends WidgetDisplay {

    void renderRows(FileDto rows);

    HasFieldUpdater<FileDto, String> getFileNameColumn();

    HasUrl getFileDownloader();

  }

  public interface HasUrl {

    public String getUrl();

    public void setUrl(String url);
  }

  /**
   * The folder currently being displayed. This is null until a request to the server succeeds (see {@code updateTable})
   * after which, this attribute should never be null.
   */
  private FileDto currentFolder;

  @Inject
  public FolderDetailsPresenter(Display display, EventBus eventBus) {
    super(display, eventBus);
  }

  @Override
  public Place getPlace() {
    return null;
  }

  @Override
  protected void onBind() {

    super.getDisplay().getFileNameColumn().setFieldUpdater(new FieldUpdater<FileDto, String>() {

      public void update(int index, FileDto file, String value) {
        if(file.getType().isFileType(FileDto.FileType.FILE)) {
          downloadFile(file.getPath());
        } else {
          updateTable(file.getPath());
          eventBus.fireEvent(new FolderSelectionChangeEvent(file));
        }
      }
    });

    super.registerHandler(eventBus.addHandler(FileSystemTreeFolderSelectionChangeEvent.getType(), new FileSystemTreeFolderSelectionChangeEvent.Handler() {

      @Override
      public void onFolderSelectionChange(FileSystemTreeFolderSelectionChangeEvent event) {
        updateTable(event.getFolder().getPath());
      }

    }));

    super.registerHandler(eventBus.addHandler(FileUploadedEvent.getType(), new FileUploadedEvent.Handler() {

      @Override
      public void onFileUploaded(FileUploadedEvent event) {
        // Refresh the current folder since a new file was probably added to it.
        refreshDisplay();
      }

    }));
  }

  @Override
  protected void onPlaceRequest(PlaceRequest request) {
  }

  @Override
  protected void onUnbind() {
  }

  @Override
  public void refreshDisplay() {
    if(currentFolder != null) {
      updateTable(currentFolder.getPath());
    } else {
      updateTable("/");
    }
  }

  @Override
  public void revealDisplay() {
    updateTable("/");
  }

  private void downloadFile(String path) {
    // TODO URL must not generated by client, do it on the server side.
    String url = new StringBuilder(GWT.getModuleBaseURL().replace(GWT.getModuleName() + "/", "")).append("ws/files").append(path).toString();
    getDisplay().getFileDownloader().setUrl(url);
  }

  private void updateTable(String path) {
    ResourceRequestBuilderFactory.<FileDto> newBuilder().forResource("/files" + path).get().withCallback(new ResourceCallback<FileDto>() {
      @Override
      public void onResource(Response response, FileDto resource) {
        currentFolder = resource;
        getDisplay().renderRows(resource);
      }
    }).send();
  }

}
