// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.174.0
//   protoc               v3.12.4
// source: Apps.proto

export const protobufPackage = 'Apps';

export interface AppDto {
  id?: string | undefined;
  name: string;
  type: string;
  cluster?: string | undefined;
  server?: string | undefined;
  tags: string[];
}

export interface AppsConfigDto {
  token: string;
  rockConfigs: RockAppConfigDto[];
}

export interface RockAppConfigDto {
  host: string;
  administratorCredentials?: AppCredentialsDto | undefined;
  managerCredentials?: AppCredentialsDto | undefined;
  userCredentials?: AppCredentialsDto | undefined;
}

export interface AppCredentialsDto {
  name: string;
  password: string;
}
