// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.174.0
//   protoc               v3.12.4
// source: Identifiers.proto

export const protobufPackage = 'Identifiers';

export interface IdentifiersMappingDto {
  name: string;
  entityTypes: string[];
}

export interface IdentifiersMappingConfigDto {
  name?: string | undefined;
  allowIdentifierGeneration?: boolean | undefined;
  ignoreUnknownIdentifier?: boolean | undefined;
}

export interface IdentifierSuggestions {
  entityType: string;
  query: string;
  limit: number;
  identifiers: string[];
}
