// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.21.12
// source: K8s.proto

export const protobufPackage = "k8s.v1";

/** “100m”, “512Mi”, … */
export interface Quantity {
  value: string;
}

export interface ResourceList {
  /** optional */
  cpu:
    | Quantity
    | undefined;
  /** optional */
  memory: Quantity | undefined;
}

export interface ResourceRequirements {
  /** min guaranteed */
  requests:
    | ResourceList
    | undefined;
  /** hard ceiling */
  limits: ResourceList | undefined;
}

export interface EnvVar {
  name: string;
  value: string;
}

export interface Container {
  name: string;
  image: string;
  port: number;
  env: EnvVar[];
  resources: ResourceRequirements | undefined;
}

export interface PodSpec {
  namespace: string;
  container: Container | undefined;
}
