// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.21.12
// source: K8s.proto

export const protobufPackage = 'K8s';

export interface ResourceListDto {
  /** optional */
  cpu: string;
  /** optional */
  memory: string;
}

export interface ResourceRequirementsDto {
  /** min guaranteed */
  requests: ResourceListDto | undefined;
  /** hard ceiling */
  limits: ResourceListDto | undefined;
}

export interface ContainerDto {
  name: string;
  image: string;
  imagePullPolicy: string;
  imagePullSecret: string;
  port: number;
  env: ContainerDto_EnvEntry[];
  resources: ResourceRequirementsDto | undefined;
}

export interface ContainerDto_EnvEntry {
  key: string;
  value: string;
}

export interface PodSpecDto {
  id: string;
  type: string;
  description: string;
  namespace: string;
  container: ContainerDto | undefined;
  enabled: boolean;
}
