// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.21.12
// source: OpalR.proto

/* eslint-disable */
import { type AppDto } from './Apps';
import { type PodSpecDto } from './K8s';
import { type EntryDto } from './Opal';

export const protobufPackage = 'OpalR';

export enum RSessionStatus {
  WAITING = 'WAITING',
  BUSY = 'BUSY',
  UNRECOGNIZED = 'UNRECOGNIZED',
}

export interface RProfileDto {
  name: string;
  enabled: boolean;
  restrictedAccess: boolean;
}

export interface RServerClusterDto {
  name: string;
  servers: RServerDto[];
}

export interface RServerDto {
  name: string;
  cluster: string;
  version: string;
  running: boolean;
  tags: string[];
  sessionCount: number;
  busySessionCount: number;
  cores: number;
  freeMemory: number;
  app?: AppDto | undefined;
  pod?: PodSpecDto | undefined;
}

export interface RSessionDto {
  id: string;
  user: string;
  creationDate: string;
  lastAccessDate: string;
  status: RSessionStatus;
  state: string;
  link?: string | undefined;
  context: string;
  profile: string;
  cluster: string;
  server: string;
  currentExecutionTimeMillis: number;
  totalExecutionTimeMillis: number;
}

export interface RPackageDto {
  name: string;
  description: EntryDto[];
  cluster: string;
  rserver: string;
}

export interface RCommandDto {
  id: string;
  script: string;
  status: string;
  createDate: string;
  withResult: boolean;
  startDate?: string | undefined;
  endDate?: string | undefined;
  error?: string | undefined;
}

export interface RWorkspaceDto {
  name: string;
  user: string;
  lastAccessDate: string;
  context: string;
  size: number;
}

export interface RRuntimeErrorDto {}

export interface RSessionActivityDto {
  user: string;
  context: string;
  profile: string;
  createdDate: string;
  updatedDate: string;
  executionTimeMillis: number;
  sessionTimeMillis?: number | undefined;
}

export interface RActivitySummaryDto {
  user: string;
  context: string;
  profile: string;
  startDate: string;
  endDate: string;
  executionTimeMillis: number;
  sessionsCount: number;
  sessionTimeMillis?: number | undefined;
}

/**
 * An allowance of R usage, for a subject, an execution context and a metric. A subject may be given one quota
 * per metric: limits of different metrics are not comparable, and are resolved independently.
 */
export interface RQuotaDto {
  id?: number | undefined;
  context: string;
  /** SYSTEM | GROUP | USER */
  subjectType: string;
  /** empty for SYSTEM */
  principal: string;
  /** DAILY | WEEKLY */
  period: string;
  /** milliseconds of whatever the metric names */
  limitMillis: number;
  enabled: boolean;
  /** EXECUTION_TIME | SESSION_TIME */
  metric: string;
}

/**
 * What a user has consumed, for one metric, against the quota that applies to them. No quota means unlimited, hence
 * the optional fields: there is no window to report when nothing is being limited.
 */
export interface RQuotaUsageDto {
  context: string;
  user: string;
  quota?: RQuotaDto | undefined;
  usedMillis: number;
  windowStartDate?: string | undefined;
  exceeded: boolean;
  nextCreditDate?: string | undefined;
  /** the metric this entry reports on */
  metric: string;
  /** sessions still open in the context, which keep spending a session time allowance */
  openSessionsCount?: number | undefined;
}
