// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.174.0
//   protoc               v3.12.4
// source: Plugins.proto

export const protobufPackage = 'Plugins';

export interface PluginPackageDto {
  name: string;
  title: string;
  description: string;
  author: string;
  maintainer: string;
  license: string;
  website?: string | undefined;
  version: string;
  opalVersion: string;
  type: string;
  file?: string | undefined;
  uninstalled?: boolean | undefined;
}

export interface PluginPackagesDto {
  site: string;
  updated?: string | undefined;
  restart: boolean;
  packages: PluginPackageDto[];
}

export interface DatasourcePluginPackageDto {
  usages: string[];
  group: string;
}

export interface AnalysisPluginPackageDto {
  analysisTemplates: AnalysisPluginTemplateDto[];
}

export interface AnalysisPluginTemplateDto {
  name: string;
  title: string;
  description?: string | undefined;
  schemaForm: string;
  valueTypes: string[];
  reportPath?: string | undefined;
  routinePath?: string | undefined;
}

export interface PluginDto {
  name: string;
  title: string;
  description: string;
  author: string;
  maintainer: string;
  license: string;
  website?: string | undefined;
  version: string;
  opalVersion: string;
  type: string;
  siteProperties: string;
}

export interface VCFStoreDto {
  name: string;
  /** VCF file names */
  vcf: string[];
  totalSamplesCount: number;
  identifiedSamplesCount?: number | undefined;
  controlSamplesCount?: number | undefined;
  participantsCount?: number | undefined;
}

export interface VCFSummaryDto {
  /** VCF file name */
  name: string;
  /** VCF/BCF */
  format: string;
  /** VCF file size */
  size: number;
  totalSamplesCount: number;
  identifiedSamplesCount?: number | undefined;
  controlSamplesCount?: number | undefined;
  participantsCount?: number | undefined;
  variantsCount: number;
  genotypesCount: number;
}

export interface VCFSamplesMappingDto {
  projectName: string;
  tableReference: string;
  participantIdVariable: string;
  sampleRoleVariable: string;
}
