// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.174.0
//   protoc               v3.12.4
// source: Resources.proto

export const protobufPackage = 'Resources';

export interface ResourceProvidersStatusDto {
  providersCount: number;
  rServerRunning: boolean;
}

export interface ResourceProvidersDto {
  providers: ResourceProviderDto[];
  categories: ResourceCategoryDto[];
}

export interface ResourceProviderDto {
  name: string;
  title: string;
  web?: string | undefined;
  description?: string | undefined;
  categories: ResourceCategoryDto[];
  resourceFactories: ResourceFactoryDto[];
}

export interface ResourceCategoryDto {
  name: string;
  title: string;
  description?: string | undefined;
}

export interface ResourceFactoryDto {
  provider: string;
  name: string;
  title: string;
  description?: string | undefined;
  tags: string[];
  parametersSchemaForm: string;
  credentialsSchemaForm: string;
}
