// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.174.0
//   protoc               v3.12.4
// source: SQL.proto

export const protobufPackage = 'SQL';

export interface SQLExecutionDto {
  user: string;
  query: string;
  datasource?: string | undefined;
  /** millis */
  start: number;
  /** millis */
  end: number;
  error?: string | undefined;
}
