// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.174.0
//   protoc               v3.12.4
// source: Ws.proto

export const protobufPackage = 'Ws';

export interface ClientErrorDto {
  /** Holds the HTTP status code (4xx) */
  code: number;
  /** Holds a one-word error descriptor. This should be usable as a key in localisation bundles. */
  status: string;
  /** Arguments to be passed during localisation */
  arguments: string[];
}

export interface ServerErrorDto {
  /** Holds the HTTP status code (5xx) */
  code: number;
  /** Holds a one-word error descriptor. This should be usable as a key in localisation bundles. */
  status: string;
  /** Arguments to be passed during localisation */
  arguments: string[];
}

export interface ConstraintViolationErrorDto {
  /** the interpolated error message for this constraint violation */
  message: string;
  /** the non-interpolated error message for this constraint violation */
  messageTemplate: string;
  propertyPath: string;
}
