/*
 * Copyright (c) 2021 OBiBa. All rights reserved.
 *
 * This program and the accompanying materials
 * are made available under the terms of the GNU Public License v3.0.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.obiba.opal.core.service;

import com.google.common.base.Strings;
import javax.validation.constraints.NotNull;
import org.h2.jdbcx.JdbcConnectionPool;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.DisposableBean;
import org.springframework.beans.factory.InitializingBean;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.concurrent.locks.Condition;
import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;

@Component
public class H2OrientDbServerFactory implements OrientDbServerFactory, InitializingBean, DisposableBean {

  private static final Logger log = LoggerFactory.getLogger(H2OrientDbServerFactory.class);

  private static final String H2_HOME = "${OPAL_HOME}/data/h2/opal-config";
  private static final String DEFAULT_URL = "jdbc:h2:" + H2_HOME + ";MODE=PostgreSQL";

  private final Lock lock = new ReentrantLock();
  private final Condition condition = lock.newCondition();

  private boolean started = false;
  private String url;
  private JdbcConnectionPool connectionPool;

  @Value(DEFAULT_URL)
  @Override
  public void setUrl(@NotNull String url) {
    this.url = url;
  }

  @Override
  public void afterPropertiesSet() throws Exception {
    start();
  }

  @Override
  public void start() throws Exception {
    stop();

    if (Strings.isNullOrEmpty(url)) {
      this.url = DEFAULT_URL;
    }

    log.info("Starting H2 config database at {}", url);
    connectionPool = JdbcConnectionPool.create(url, "sa", "");
    connectionPool.setMaxConnections(20);

    initializeSchema();

    started = true;
    signalCondition();
  }

  private void initializeSchema() throws SQLException {
    try (Connection conn = connectionPool.getConnection();
         Statement stmt = conn.createStatement()) {
      stmt.execute("""
          CREATE TABLE IF NOT EXISTS documents (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              entity_type VARCHAR(255) NOT NULL,
              unique_key VARCHAR(4096) NOT NULL,
              document CLOB NOT NULL,
              created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              CONSTRAINT uk_entity_unique_key UNIQUE (entity_type, unique_key)
          )
          """);
      stmt.execute("CREATE INDEX IF NOT EXISTS idx_entity_type ON documents(entity_type)");
      log.info("H2 schema initialized successfully");
    }
  }

  @Override
  public void destroy() {
    stop();
  }

  @Override
  public void stop() {
    if (connectionPool != null) {
      log.info("Stopping H2 config database");
      connectionPool.dispose();
      connectionPool = null;
    }
    started = false;
  }

  @NotNull
  @Override
  public Connection getConnection() throws SQLException {
    try {
      waitForCondition();
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }
    return connectionPool.getConnection();
  }

  private void waitForCondition() throws InterruptedException {
    lock.lock();
    try {
      while (!started) {
        condition.await();
      }
    } finally {
      lock.unlock();
    }
  }

  private void signalCondition() {
    lock.lock();
    try {
      started = true;
      condition.signalAll();
    } finally {
      lock.unlock();
    }
  }
}
