/*
 * Copyright (c) 2013 OBiBa. All rights reserved.
 *
 * This program and the accompanying materials
 * are made available under the terms of the GNU Public License v3.0.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.obiba.opal.web.gwt.ace.client;

import com.google.gwt.core.client.JavaScriptObject;

/**
 *
 */
public class AceEditorWrapper extends JavaScriptObject {

  protected AceEditorWrapper() {}

  @SuppressWarnings("StaticMethodOnlyUsedInOneClass")
  public static native AceEditorWrapper createEditor(String elementId) /*-{
      var editor = $wnd.ace.edit(elementId);
      editor.setTheme("ace/theme/textmate");
      editor.getSession().setMode("ace/mode/javascript");
      return editor;
  }-*/;

  /**
   * Get the current editor content.
   */
  public final native String getValue() /*-{
      return this.getValue();
  }-*/;

  /**
   * Set the editor content.
   */
  public final native void setValue(String value) /*-{
      this.setValue(value);
  }-*/;

  /**
   * Get selected text
   */
  public final native String getSelectedText() /*-{
      return this.getSession().getTextRange(this.getSelectionRange());
  }-*/;

  /**
   * Register a handler for change events generated by the editor.
   *
   * @param callback the change event handler
   */
  public final native void addOnChangeHandler(AceEditorCallback callback) /*-{
      this.getSession().on("change", function (e) {
          callback.@org.obiba.opal.web.gwt.ace.client.AceEditorCallback::invokeAceCallback(Lcom/google/gwt/core/client/JavaScriptObject;)(e);
      });
  }-*/;

}
