ALTER TABLE qrtz_job_details  ALTER COLUMN JOB_DATA BLOB;
ALTER TABLE qrtz_triggers ALTER COLUMN JOB_DATA BLOB;
ALTER TABLE qrtz_blob_triggers ALTER COLUMN BLOB_DATA BLOB;
ALTER TABLE qrtz_calendars ALTER COLUMN CALENDAR BLOB;